site_name: COLORPARSE

theme:
        name: 'readthedocs'
        highlightjs: true
        hljs_languages:
                - python
                - bash
                - console

nav:
- Getting Started: 'index.md'
- Module Content: 'module-content.md'
- Terminal Usage: 'terminal.md'
- Further Reading: 'further-reading.md'


markdown_extensions:
        - toc:
                permalink: "&para;"
