def _dprint(*values: object) -> None: ...
def _get_typename(obj: object) -> str: ...
def _get_repr(obj: object) -> str: ...
def _odir(obj: object) -> list[object]: ...
def _any_in(value: str, items: list[str]) -> bool: ...
def _in_any(value: str, items: list[str]) -> bool: ...
def _break_str(input_string: str, max_len: int) -> str: ...
