#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import re

from colorparse import _main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(_main())
